# Workflow for deploying WasmJS App to GitHub Pages
name: Deploy WasmJS App to GitHub Pages and Send Artifact URL

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read  # Required to fetch the repository content
  pages: write    # Allow deployment to GitHub Pages
  id-token: write # Required by actions/configure-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "‚úÖ Checkout code"
        uses: actions/checkout@v4

      - name: "‚öôÔ∏è Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Update local.properties
        run: |
          chmod +x .github/scripts/update_properties.sh
          .github/scripts/update_properties.sh
        env:
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: "üõ†Ô∏è Build WasmJS App"
        run: gradle :composeApp:wasmJsBrowserDistribution

      - name: "Upload artifact"
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: memorchess-wasm
          path: composeApp/build/dist/wasmJs/productionExecutable/
          retention-days: 1

      - name: "Send artifact url"
        env:
          TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
        run: |
          artifactUrl="${{ steps.upload-artifact.outputs.artifact-url }}"

          payload=$(cat <<EOF
          {
            "event_type": "update-memorchess",
            "client_payload": {
              "message": "$artifactUrl"
            }
          }
          EOF
          )

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$payload" \
            https://api.github.com/repos/Axl-Lvy/Axl-Lvy/dispatches

      - name: "üìÑ Configure GitHub Pages"
        uses: actions/configure-pages@v5

      - name: "üì§ Upload GitHub Pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./composeApp/build/dist/wasmJs/productionExecutable

      - name: "üöÄ Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4